[cerebrium.deployment]
name = "cooking-llama-train"
python_version = "3.11"
docker_base_image_url = "debian:bookworm-slim"
disable_auth = false
include = ["main.py", "cerebrium.toml", "model.py", "dataset.py", "download_weights.py", "train.py"]

[cerebrium.dependencies.paths]
pip = "requirements.txt"

[cerebrium.hardware]
cpu = 4
memory = 16.0
compute = "AMPERE_A10"
gpu_count = 1

[cerebrium.scaling]
min_replicas = 0
max_replicas = 1
cooldown = 10
replica_concurrency = 1
response_grace_period = 900
scaling_metric = "concurrency_utilization"
scaling_target = 100
scaling_buffer = 0
roll_out_duration_seconds = 0